kind: Deployment
apiVersion: apps/v1
metadata:
  name: gohttpserver
  namespace: staging
  labels:
    app.kubernetes.io/name: gohttpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gohttpserver
  template:
    metadata:
      name: gohttpserver
      labels:
        app.kubernetes.io/name: gohttpserver
    spec:
      containers:
        - name: gohttpserver
          image: gohttpserver
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 100Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 20
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: gohttpserver
  namespace: staging
  labels:
    app.kubernetes.io/name: gohttpserver
spec:
  selector:
    app.kubernetes.io/name: gohttpserver
  type: ClusterIP
  ports:
  - name: traffic-port
    protocol: TCP
    port: 20000
    targetPort: 20000